---
- name: Generate admin password
  # MD5 password has to be salted with username
  ansible.builtin.shell: "echo md5$(echo -n '{{ admin_password }}{{ admin_user }}' | md5sum | awk '{print $1}')"
  register: admin_password_hash
  changed_when: false
- debug: msg="{{ admin_user }} password hash is {{ admin_password_hash.stdout }}"
  tags: ["configuration"]

- name: Create superuser, set MD5-hashed password, grant privs
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    name: "{{ admin_user }}"
    password: "{{ admin_password_hash.stdout }}"
    role_attr_flags: SUPERUSER
    state: present
  tags: ["configuration"]
