---
- name: Import RPM key
  ansible.builtin.rpm_key:
    state: present
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial

- name: Install PostgreSQL
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items: "{{ packages }}"
  tags:
    - installation
    - packages

- name: Check PostgreSQL initialization
  ansible.builtin.stat:
    path: /var/lib/pgsql/initdb_postgresql.log
  register: pg_initialized

- name: Initialize PostgreSQL
  ansible.builtin.shell: postgresql-setup --initdb
  when: not pg_initialized.stat.exists
