---
# Debian PostgreSQL installation automatically calls initdb i.e. it initializes the cluster with default encoding and locale. 
# To change the locale (and possibly other options in initdb), delete the existing default cluster and create a new one.

- name: Check PostgreSQL initialization
  ansible.builtin.find:
    path: /var/lib/pgsql/data
  register: pg_initialized
  when: ansible_facts['os_family'] == 'RedHat'
  tags:
    - initialization

- name: Initialize PostgreSQL
  ansible.builtin.shell: postgresql-setup --initdb
  when: (ansible_facts['os_family'] == 'RedHat') and (pg_initialized.matched == 0)
  tags:
    - initialization

- name: Start and enable PostgreSQL
  ansible.builtin.systemd:
    enabled: true
    name: postgresql
    state: started
  tags:
    - initialization