---
- name: Generate DBA password
  # MD5 password has to be salted by concatenating password username
  ansible.builtin.shell: "echo md5$(echo -n 'passworddba' | md5sum | awk '{print $1}')"
  register: dba_password_hash
  changed_when: false
  tags:
    - dba-password

# - debug: 
#     msg: "DBA password hash is {{ dba_password_hash.stdout }}"

- name: Create DBA
  become_user: postgres
  community.postgresql.postgresql_user:
    name: dba
    password: "{{ dba_password_hash.stdout }}"
    role_attr_flags: SUPERUSER
    state: present
  tags:
    - create-dba